100DersteMVC/100DersteMVC/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _100DersteMVC.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager headingManager = new HeadingManager(new EFHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EFCategoryDal());
        WriterManager writerManager = new WriterManager(new EFWriterDal());

        public ActionResult Index()
        {
            var headingValues = headingManager.GetList();
            return View(headingValues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.ValueCategoryDropdown = valueCategory;
            List<SelectListItem> valueWriter = (from x in writerManager.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName+" "+x.WriterSurName,
                                                    Value = x.WriterID.ToString()
                                                }).ToList();
            ViewBag.ValueWriterDropdown = valueWriter;
            return View();
        }
        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            headingManager.HeadingAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valueCategory;

            var headingValue = headingManager.GetByID(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            headingManager.HeadingUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.GetByID(id);
            headingValue.HeadingStatus = false;
            headingManager.HeadingDelete(headingValue);
            return RedirectToAction("Index");
        }

       
    }
}

100DersteMVC/100DersteMVC/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using FluentValidation.Results;
using BusinessLayer.FluentValidation;

namespace _100DersteMVC.Controllers
{
    public class WriterPanelController : Controller
    {
        // GET: WriterPanel
        HeadingManager headingManager = new HeadingManager(new EFHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EFCategoryDal());
        WriterManager writerManager = new WriterManager(new EFWriterDal());
        Context c = new Context();

        [HttpGet]
        public ActionResult WriterProfile(int id=0)
        {
            string p = (string)Session["WriterMail"];
            id = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var writerValue = writerManager.GetByID(id);
            return View(writerValue);
        }

        [HttpPost]
        public ActionResult WriterProfile(Writer p)
        {
            WriterValidator writerValidator = new WriterValidator();
            ValidationResult result =writerValidator.Validate(p);
            if (result.IsValid)
            {
                writerManager.WriterUpdate(p);
                return RedirectToAction("WriterProfile");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }

        public ActionResult MyHeading(string p)
        {
            
            p = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var values = headingManager.GetListByWriter(writerIdInfo);
            return View(values);
        }
        [HttpGet]
        public ActionResult NewHeading()
        {
           
            
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.ValueCategoryDropdown = valueCategory;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading p)
        {
            string m = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == m).Select(y => y.WriterID).FirstOrDefault();
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writerIdInfo;
            p.HeadingStatus = true;
            headingManager.HeadingAdd(p);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valueCategory;

            var headingValue = headingManager.GetByID(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            headingManager.HeadingUpdate(p);
            return RedirectToAction("MyHeading");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.GetByID(id);
            headingValue.HeadingStatus = false;
            headingManager.HeadingDelete(headingValue);
            return RedirectToAction("MyHeading");
        }

        public ActionResult AllHeading(int p=1)
        {
            var headings = headingManager.GetList().ToPagedList(p,4);
            return View(headings);
        }
    }
}

100DersteMVC/100DersteMVC/Views/WriterPanel/AllHeading.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>

@{
    ViewBag.Title = "AllHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{ string color = "";}
@{ string colorStatus = "";}
@{ string colorStatus2 = "";}
@{ string status = "";}
@{ string statusTurn = "";}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>

                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>

                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryID == 1)
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryID == 2)
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryID == 3)
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryID == 4)
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryID == 5)
                            {
                                color = "badge badge-dark";
                            }
                            if (item.Category.CategoryID == 6)
                            {
                                color = "badge badge-info";
                            }
                            if (item.HeadingStatus == false)
                            {
                                colorStatus = "danger";
                                status = "PASİF";
                                statusTurn = "Aktif Et ";
                            }
                            if (item.HeadingStatus == true)
                            {
                                colorStatus = "success";
                                status = "AKTİF";
                                statusTurn = "Pasif Yap";
                            }
                            if (item.HeadingStatus == true)
                            {
                                colorStatus2 = "danger";
                            }
                            if (item.HeadingStatus == false)
                            {
                                colorStatus2 = "success";
                            }

                            <tr>

                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Default/Headings/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanelContent/AddContent/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Bu Başlığa Yaz
                                    </a>
                                    
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
@Html.PagedListPager((IPagedList)Model, p => Url.Action("AllHeading", new {p}),new PagedListRenderOptions
{
    LiElementClasses=new List<string>
    {
        "page-link"
    }
})

100DersteMVC/100DersteMVC/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h2>Başlık Düzenleme</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        
        @Html.HiddenFor(x => x.HeadingID)
        @Html.HiddenFor(x => x.HeadingDate)
        @Html.HiddenFor(x => x.WriterID)
        
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>

}

100DersteMVC/100DersteMVC/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


@{ string color = "";}
@{ string colorStatus = "";}
@{ string colorStatus2 = "";}
@{ string status = "";}
@{ string statusTurn = "";}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>

                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                         
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryID == 1)
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryID == 2)
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryID == 3)
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryID == 4)
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryID == 5)
                            {
                                color = "badge badge-dark";
                            }
                            if (item.Category.CategoryID == 6)
                            {
                                color = "badge badge-info";
                            }
                            if (item.HeadingStatus == false)
                            {
                                colorStatus = "danger";
                                status = "PASİF";
                                statusTurn = "Aktif Et ";
                            }
                            if (item.HeadingStatus == true)
                            {
                                colorStatus = "success";
                                status = "AKTİF";
                                statusTurn = "Pasif Yap";
                            }
                            if (item.HeadingStatus == true)
                            {
                                colorStatus2 = "danger";
                            }
                            if (item.HeadingStatus == false)
                            {
                                colorStatus2 = "success";
                            }

                            <tr>

                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-@colorStatus2 btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        @statusTurn
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
<a href="/WriterPanel/NewHeading/" class="btn btn-primary">Yeni Başlık Girişi</a>
</html>

100DersteMVC/100DersteMVC/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Yeni Başlık Ekleme</h2>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.ValueCategoryDropdown, new { @class = "form-control" })
        <br /><br />
        <button class="btn btn-primary">Başlığı Oluştur</button>
    </div>
}

100DersteMVC/100DersteMVC/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<br />
<h2>Yazar Profil Düzenleme</h2>
@using (Html.BeginForm("WriterProfile", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
       
        @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
        
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br />
        @Html.Label("Yazar Başlık")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Görsel")
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        <br /><br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}